//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RevopointScanAutomation.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.5.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Program Files\\Revo Scan 5\\RevoScan5.exe")]
        public string SavedValue_RevoScanApplicationPath {
            get {
                return ((string)(this["SavedValue_RevoScanApplicationPath"]));
            }
            set {
                this["SavedValue_RevoScanApplicationPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int SavedValue_PauseTime {
            get {
                return ((int)(this["SavedValue_PauseTime"]));
            }
            set {
                this["SavedValue_PauseTime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1440")]
        public int SavedValue_StartButtonX {
            get {
                return ((int)(this["SavedValue_StartButtonX"]));
            }
            set {
                this["SavedValue_StartButtonX"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("322")]
        public int SavedValue_StartButtonY {
            get {
                return ((int)(this["SavedValue_StartButtonY"]));
            }
            set {
                this["SavedValue_StartButtonY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1600")]
        public int SavedValue_RevoScanWindowWidth {
            get {
                return ((int)(this["SavedValue_RevoScanWindowWidth"]));
            }
            set {
                this["SavedValue_RevoScanWindowWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("900")]
        public int SavedValue_RevoScanWindowHeight {
            get {
                return ((int)(this["SavedValue_RevoScanWindowHeight"]));
            }
            set {
                this["SavedValue_RevoScanWindowHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int SavedValue_ScanDuration {
            get {
                return ((int)(this["SavedValue_ScanDuration"]));
            }
            set {
                this["SavedValue_ScanDuration"] = value;
            }
        }
    }
}
